module "repo-opentelemetry-python-contrib" {
  source = "./modules/repository"
  name   = "opentelemetry-python-contrib"
  description = "OpenTelemetry instrumentation for Python modules"
  has_projects = true
  has_discussions = true
  allow_update_branch = true
  allow_auto_merge = true
}

resource "github_repository_collaborators" "opentelemetry-python-contrib" {
  repository = "opentelemetry-python-contrib"

  team {
    team_id = github_team.opentelemetry-python-contrib-approvers.id
    permission = "push"
  }

  team {
    team_id = github_team.opentelemetry-python-contrib-maintainers.id
    permission = "admin"
  }

  # this is really an org-level role, but it needs to be specified here
  # to avoid false positives showing up in the plan
  # (see underlying bug at https://github.com/integrations/terraform-provider-github/issues/2445)
  team {
    team_id = github_team.governance-committee.id
    permission = "push"
  }

  # this is really an org-level role, but it needs to be specified here
  # to avoid false positives showing up in the plan
  # (see underlying bug at https://github.com/integrations/terraform-provider-github/issues/2445)
  team {
    team_id = github_team.sig-security-maintainers.id
    permission = "pull"
  }
}

module "branch-protection-rule-opentelemetry-python-contrib-0" {
  source = "./modules/branch-protection-long-term"
  repository_id = module.repo-opentelemetry-python-contrib.node_id
  pattern = "main"
  require_code_owner_reviews = false
  additional_required_status_checks = [
    "distro",
    "distro 3.10 Ubuntu",
    "distro 3.11 Ubuntu",
    "distro 3.12 Ubuntu",
    "distro 3.9 Ubuntu",
    "docker-tests",
    "docs",
    "exporter-prometheus-remote-write",
    "exporter-prometheus-remote-write 3.10 Ubuntu",
    "exporter-prometheus-remote-write 3.11 Ubuntu",
    "exporter-prometheus-remote-write 3.12 Ubuntu",
    "exporter-prometheus-remote-write 3.9 Ubuntu",
    "exporter-richconsole",
    "exporter-richconsole 3.10 Ubuntu",
    "exporter-richconsole 3.11 Ubuntu",
    "exporter-richconsole 3.12 Ubuntu",
    "exporter-richconsole 3.9 Ubuntu",
    "generate",
    "generate-workflows",
    "instrumentation-aio-pika",
    "instrumentation-aio-pika-0 3.10 Ubuntu",
    "instrumentation-aio-pika-0 3.11 Ubuntu",
    "instrumentation-aio-pika-0 3.12 Ubuntu",
    "instrumentation-aio-pika-0 3.9 Ubuntu",
    "instrumentation-aio-pika-1 3.10 Ubuntu",
    "instrumentation-aio-pika-1 3.11 Ubuntu",
    "instrumentation-aio-pika-1 3.12 Ubuntu",
    "instrumentation-aio-pika-1 3.9 Ubuntu",
    "instrumentation-aio-pika-2 3.10 Ubuntu",
    "instrumentation-aio-pika-2 3.11 Ubuntu",
    "instrumentation-aio-pika-2 3.12 Ubuntu",
    "instrumentation-aio-pika-2 3.9 Ubuntu",
    "instrumentation-aio-pika-3 3.10 Ubuntu",
    "instrumentation-aio-pika-3 3.11 Ubuntu",
    "instrumentation-aio-pika-3 3.12 Ubuntu",
    "instrumentation-aio-pika-3 3.9 Ubuntu",
    "instrumentation-aiohttp-client",
    "instrumentation-aiohttp-client 3.10 Ubuntu",
    "instrumentation-aiohttp-client 3.11 Ubuntu",
    "instrumentation-aiohttp-client 3.12 Ubuntu",
    "instrumentation-aiohttp-client 3.9 Ubuntu",
    "instrumentation-aiohttp-server",
    "instrumentation-aiohttp-server 3.10 Ubuntu",
    "instrumentation-aiohttp-server 3.11 Ubuntu",
    "instrumentation-aiohttp-server 3.12 Ubuntu",
    "instrumentation-aiohttp-server 3.9 Ubuntu",
    "instrumentation-aiopg",
    "instrumentation-aiopg 3.10 Ubuntu",
    "instrumentation-aiopg 3.11 Ubuntu",
    "instrumentation-aiopg 3.12 Ubuntu",
    "instrumentation-aiopg 3.9 Ubuntu",
    "instrumentation-asgi",
    "instrumentation-asgi 3.10 Ubuntu",
    "instrumentation-asgi 3.11 Ubuntu",
    "instrumentation-asgi 3.12 Ubuntu",
    "instrumentation-asgi 3.9 Ubuntu",
    "instrumentation-asyncio",
    "instrumentation-asyncio 3.10 Ubuntu",
    "instrumentation-asyncio 3.11 Ubuntu",
    "instrumentation-asyncio 3.12 Ubuntu",
    "instrumentation-asyncio 3.9 Ubuntu",
    "instrumentation-asyncpg",
    "instrumentation-asyncpg 3.10 Ubuntu",
    "instrumentation-asyncpg 3.11 Ubuntu",
    "instrumentation-asyncpg 3.12 Ubuntu",
    "instrumentation-asyncpg 3.9 Ubuntu",
    "instrumentation-aws-lambda",
    "instrumentation-aws-lambda 3.10 Ubuntu",
    "instrumentation-aws-lambda 3.11 Ubuntu",
    "instrumentation-aws-lambda 3.12 Ubuntu",
    "instrumentation-aws-lambda 3.9 Ubuntu",
    "instrumentation-boto",
    "instrumentation-boto 3.10 Ubuntu",
    "instrumentation-boto 3.11 Ubuntu",
    "instrumentation-boto 3.9 Ubuntu",
    "instrumentation-boto3sqs",
    "instrumentation-boto3sqs 3.10 Ubuntu",
    "instrumentation-boto3sqs 3.11 Ubuntu",
    "instrumentation-boto3sqs 3.12 Ubuntu",
    "instrumentation-boto3sqs 3.9 Ubuntu",
    "instrumentation-botocore",
    "instrumentation-botocore-0 3.10 Ubuntu",
    "instrumentation-cassandra",
    "instrumentation-cassandra 3.10 Ubuntu",
    "instrumentation-cassandra 3.11 Ubuntu",
    "instrumentation-cassandra 3.12 Ubuntu",
    "instrumentation-cassandra 3.9 Ubuntu",
    "instrumentation-celery",
    "instrumentation-celery 3.10 Ubuntu",
    "instrumentation-celery 3.11 Ubuntu",
    "instrumentation-celery 3.12 Ubuntu",
    "instrumentation-celery 3.9 Ubuntu",
    "instrumentation-confluent-kafka",
    "instrumentation-confluent-kafka 3.10 Ubuntu",
    "instrumentation-confluent-kafka 3.11 Ubuntu",
    "instrumentation-confluent-kafka 3.12 Ubuntu",
    "instrumentation-confluent-kafka 3.9 Ubuntu",
    "instrumentation-dbapi",
    "instrumentation-dbapi 3.10 Ubuntu",
    "instrumentation-dbapi 3.11 Ubuntu",
    "instrumentation-dbapi 3.12 Ubuntu",
    "instrumentation-django",
    "instrumentation-django-0 3.9 Ubuntu",
    "instrumentation-django-1 3.10 Ubuntu",
    "instrumentation-django-1 3.11 Ubuntu",
    "instrumentation-django-1 3.12 Ubuntu",
    "instrumentation-django-1 3.9 Ubuntu",
    "instrumentation-django-2 3.9 Ubuntu",
    "instrumentation-django-3 3.10 Ubuntu",
    "instrumentation-django-3 3.11 Ubuntu",
    "instrumentation-django-3 3.12 Ubuntu",
    "instrumentation-elasticsearch",
    "instrumentation-elasticsearch-0 3.10 Ubuntu",
    "instrumentation-elasticsearch-0 3.11 Ubuntu",
    "instrumentation-elasticsearch-0 3.12 Ubuntu",
    "instrumentation-elasticsearch-0 3.9 Ubuntu",
    "instrumentation-elasticsearch-1 3.10 Ubuntu",
    "instrumentation-elasticsearch-1 3.11 Ubuntu",
    "instrumentation-elasticsearch-1 3.12 Ubuntu",
    "instrumentation-elasticsearch-1 3.9 Ubuntu",
    "instrumentation-elasticsearch-2 3.10 Ubuntu",
    "instrumentation-elasticsearch-2 3.11 Ubuntu",
    "instrumentation-elasticsearch-2 3.12 Ubuntu",
    "instrumentation-elasticsearch-2 3.9 Ubuntu",
    "instrumentation-falcon",
    "instrumentation-falcon-0 3.9 Ubuntu",
    "instrumentation-falcon-1 3.10 Ubuntu",
    "instrumentation-falcon-1 3.11 Ubuntu",
    "instrumentation-falcon-1 3.12 Ubuntu",
    "instrumentation-falcon-1 3.9 Ubuntu",
    "instrumentation-falcon-2 3.10 Ubuntu",
    "instrumentation-falcon-2 3.11 Ubuntu",
    "instrumentation-falcon-2 3.12 Ubuntu",
    "instrumentation-falcon-2 3.9 Ubuntu",
    "instrumentation-fastapi",
    "instrumentation-fastapi 3.10 Ubuntu",
    "instrumentation-fastapi 3.11 Ubuntu",
    "instrumentation-fastapi 3.12 Ubuntu",
    "instrumentation-fastapi 3.9 Ubuntu",
    "instrumentation-flask",
    "instrumentation-flask-0 3.10 Ubuntu",
    "instrumentation-flask-0 3.11 Ubuntu",
    "instrumentation-flask-0 3.12 Ubuntu",
    "instrumentation-flask-0 3.9 Ubuntu",
    "instrumentation-flask-1 3.10 Ubuntu",
    "instrumentation-flask-1 3.11 Ubuntu",
    "instrumentation-flask-1 3.12 Ubuntu",
    "instrumentation-flask-1 3.9 Ubuntu",
    "instrumentation-flask-2 3.10 Ubuntu",
    "instrumentation-flask-2 3.11 Ubuntu",
    "instrumentation-flask-2 3.12 Ubuntu",
    "instrumentation-flask-2 3.9 Ubuntu",
    "instrumentation-grpc",
    "instrumentation-grpc-0 3.10 Ubuntu",
    "instrumentation-grpc-0 3.11 Ubuntu",
    "instrumentation-grpc-0 3.12 Ubuntu",
    "instrumentation-grpc-0 3.9 Ubuntu",
    "instrumentation-grpc-1 3.10 Ubuntu",
    "instrumentation-grpc-1 3.11 Ubuntu",
    "instrumentation-grpc-1 3.12 Ubuntu",
    "instrumentation-grpc-1 3.9 Ubuntu",
    "instrumentation-httpx",
    "instrumentation-httpx-0 3.10 Ubuntu",
    "instrumentation-httpx-0 3.11 Ubuntu",
    "instrumentation-httpx-0 3.12 Ubuntu",
    "instrumentation-httpx-0 3.9 Ubuntu",
    "instrumentation-httpx-1 3.10 Ubuntu",
    "instrumentation-httpx-1 3.11 Ubuntu",
    "instrumentation-httpx-1 3.12 Ubuntu",
    "instrumentation-httpx-1 3.9 Ubuntu",
    "instrumentation-jinja2",
    "instrumentation-jinja2 3.10 Ubuntu",
    "instrumentation-jinja2 3.11 Ubuntu",
    "instrumentation-jinja2 3.12 Ubuntu",
    "instrumentation-jinja2 3.9 Ubuntu",
    "instrumentation-kafka-python",
    "instrumentation-kafka-python 3.10 Ubuntu",
    "instrumentation-kafka-python 3.11 Ubuntu",
    "instrumentation-kafka-python 3.9 Ubuntu",
    "instrumentation-kafka-pythonng 3.10 Ubuntu",
    "instrumentation-kafka-pythonng 3.11 Ubuntu",
    "instrumentation-kafka-pythonng 3.12 Ubuntu",
    "instrumentation-kafka-pythonng 3.9 Ubuntu",
    "instrumentation-logging",
    "instrumentation-logging 3.10 Ubuntu",
    "instrumentation-logging 3.11 Ubuntu",
    "instrumentation-logging 3.12 Ubuntu",
    "instrumentation-logging 3.9 Ubuntu",
    "instrumentation-mysql",
    "instrumentation-mysql-0 3.10 Ubuntu",
    "instrumentation-mysql-0 3.11 Ubuntu",
    "instrumentation-mysql-0 3.12 Ubuntu",
    "instrumentation-mysql-0 3.9 Ubuntu",
    "instrumentation-mysql-1 3.10 Ubuntu",
    "instrumentation-mysql-1 3.11 Ubuntu",
    "instrumentation-mysql-1 3.12 Ubuntu",
    "instrumentation-mysql-1 3.9 Ubuntu",
    "instrumentation-mysqlclient",
    "instrumentation-mysqlclient 3.10 Ubuntu",
    "instrumentation-mysqlclient 3.11 Ubuntu",
    "instrumentation-mysqlclient 3.12 Ubuntu",
    "instrumentation-mysqlclient 3.9 Ubuntu",
    "instrumentation-openai-v2-latest 3.10 Ubuntu",
    "instrumentation-openai-v2-latest 3.11 Ubuntu",
    "instrumentation-openai-v2-latest 3.12 Ubuntu",
    "instrumentation-openai-v2-latest 3.13 Ubuntu",
    "instrumentation-openai-v2-latest 3.9 Ubuntu",
    "instrumentation-openai-v2-oldest 3.10 Ubuntu",
    "instrumentation-openai-v2-oldest 3.11 Ubuntu",
    "instrumentation-openai-v2-oldest 3.12 Ubuntu",
    "instrumentation-openai-v2-oldest 3.13 Ubuntu",
    "instrumentation-openai-v2-oldest 3.9 Ubuntu",
    "instrumentation-psycopg",
    "instrumentation-psycopg 3.10 Ubuntu",
    "instrumentation-psycopg 3.11 Ubuntu",
    "instrumentation-psycopg 3.12 Ubuntu",
    "instrumentation-psycopg 3.9 Ubuntu",
    "instrumentation-psycopg2",
    "instrumentation-psycopg2 3.10 Ubuntu",
    "instrumentation-psycopg2 3.11 Ubuntu",
    "instrumentation-psycopg2 3.12 Ubuntu",
    "instrumentation-psycopg2 3.9 Ubuntu",
    "instrumentation-pymemcache",
    "instrumentation-pymemcache-0 3.10 Ubuntu",
    "instrumentation-pymemcache-0 3.11 Ubuntu",
    "instrumentation-pymemcache-0 3.12 Ubuntu",
    "instrumentation-pymemcache-0 3.9 Ubuntu",
    "instrumentation-pymemcache-1 3.10 Ubuntu",
    "instrumentation-pymemcache-1 3.11 Ubuntu",
    "instrumentation-pymemcache-1 3.12 Ubuntu",
    "instrumentation-pymemcache-1 3.9 Ubuntu",
    "instrumentation-pymemcache-2 3.10 Ubuntu",
    "instrumentation-pymemcache-2 3.11 Ubuntu",
    "instrumentation-pymemcache-2 3.12 Ubuntu",
    "instrumentation-pymemcache-2 3.9 Ubuntu",
    "instrumentation-pymemcache-3 3.10 Ubuntu",
    "instrumentation-pymemcache-3 3.11 Ubuntu",
    "instrumentation-pymemcache-3 3.12 Ubuntu",
    "instrumentation-pymemcache-3 3.9 Ubuntu",
    "instrumentation-pymemcache-4 3.10 Ubuntu",
    "instrumentation-pymemcache-4 3.11 Ubuntu",
    "instrumentation-pymemcache-4 3.12 Ubuntu",
    "instrumentation-pymemcache-4 3.9 Ubuntu",
    "instrumentation-pymongo",
    "instrumentation-pymongo 3.10 Ubuntu",
    "instrumentation-pymongo 3.11 Ubuntu",
    "instrumentation-pymongo 3.12 Ubuntu",
    "instrumentation-pymongo 3.9 Ubuntu",
    "instrumentation-pymysql",
    "instrumentation-pymysql 3.10 Ubuntu",
    "instrumentation-pymysql 3.11 Ubuntu",
    "instrumentation-pymysql 3.12 Ubuntu",
    "instrumentation-pymysql 3.9 Ubuntu",
    "instrumentation-pyramid",
    "instrumentation-pyramid 3.10 Ubuntu",
    "instrumentation-pyramid 3.11 Ubuntu",
    "instrumentation-pyramid 3.12 Ubuntu",
    "instrumentation-pyramid 3.9 Ubuntu",
    "instrumentation-redis",
    "instrumentation-redis 3.10 Ubuntu",
    "instrumentation-redis 3.11 Ubuntu",
    "instrumentation-redis 3.12 Ubuntu",
    "instrumentation-redis 3.9 Ubuntu",
    "instrumentation-remoulade",
    "instrumentation-remoulade 3.10 Ubuntu",
    "instrumentation-remoulade 3.11 Ubuntu",
    "instrumentation-remoulade 3.12 Ubuntu",
    "instrumentation-remoulade 3.9 Ubuntu",
    "instrumentation-requests",
    "instrumentation-requests 3.10 Ubuntu",
    "instrumentation-requests 3.11 Ubuntu",
    "instrumentation-requests 3.12 Ubuntu",
    "instrumentation-requests 3.9 Ubuntu",
    "instrumentation-sio-pika",
    "instrumentation-sio-pika-0 3.10 Ubuntu",
    "instrumentation-sio-pika-0 3.11 Ubuntu",
    "instrumentation-sio-pika-0 3.12 Ubuntu",
    "instrumentation-sio-pika-0 3.9 Ubuntu",
    "instrumentation-sio-pika-1 3.10 Ubuntu",
    "instrumentation-sio-pika-1 3.11 Ubuntu",
    "instrumentation-sio-pika-1 3.12 Ubuntu",
    "instrumentation-sio-pika-1 3.9 Ubuntu",
    "instrumentation-sqlalchemy",
    "instrumentation-sqlalchemy-1 3.10 Ubuntu",
    "instrumentation-sqlalchemy-1 3.11 Ubuntu",
    "instrumentation-sqlalchemy-1 3.12 Ubuntu",
    "instrumentation-sqlalchemy-1 3.9 Ubuntu",
    "instrumentation-sqlite3",
    "instrumentation-sqlite3 3.10 Ubuntu",
    "instrumentation-sqlite3 3.11 Ubuntu",
    "instrumentation-sqlite3 3.12 Ubuntu",
    "instrumentation-sqlite3 3.9 Ubuntu",
    "instrumentation-starlette",
    "instrumentation-starlette-latest 3.10 Ubuntu",
    "instrumentation-starlette-latest 3.11 Ubuntu",
    "instrumentation-starlette-latest 3.12 Ubuntu",
    "instrumentation-starlette-latest 3.13 Ubuntu",
    "instrumentation-starlette-latest 3.9 Ubuntu",
    "instrumentation-starlette-oldest 3.10 Ubuntu",
    "instrumentation-starlette-oldest 3.11 Ubuntu",
    "instrumentation-starlette-oldest 3.12 Ubuntu",
    "instrumentation-starlette-oldest 3.13 Ubuntu",
    "instrumentation-starlette-oldest 3.9 Ubuntu",
    "instrumentation-system-metrics",
    "instrumentation-system-metrics 3.10 Ubuntu",
    "instrumentation-system-metrics 3.11 Ubuntu",
    "instrumentation-system-metrics 3.12 Ubuntu",
    "instrumentation-system-metrics 3.9 Ubuntu",
    "instrumentation-threading",
    "instrumentation-threading 3.10 Ubuntu",
    "instrumentation-threading 3.11 Ubuntu",
    "instrumentation-threading 3.12 Ubuntu",
    "instrumentation-threading 3.9 Ubuntu",
    "instrumentation-tornado",
    "instrumentation-tornado 3.10 Ubuntu",
    "instrumentation-tornado 3.11 Ubuntu",
    "instrumentation-tornado 3.12 Ubuntu",
    "instrumentation-tornado 3.9 Ubuntu",
    "instrumentation-tortoiseorm",
    "instrumentation-tortoiseorm 3.10 Ubuntu",
    "instrumentation-tortoiseorm 3.11 Ubuntu",
    "instrumentation-tortoiseorm 3.12 Ubuntu",
    "instrumentation-tortoiseorm 3.9 Ubuntu",
    "instrumentation-urllib",
    "instrumentation-urllib 3.10 Ubuntu",
    "instrumentation-urllib 3.11 Ubuntu",
    "instrumentation-urllib 3.12 Ubuntu",
    "instrumentation-urllib 3.9 Ubuntu",
    "instrumentation-urllib3",
    "instrumentation-urllib3-0 3.10 Ubuntu",
    "instrumentation-urllib3-0 3.11 Ubuntu",
    "instrumentation-urllib3-0 3.12 Ubuntu",
    "instrumentation-urllib3-0 3.9 Ubuntu",
    "instrumentation-urllib3-1 3.10 Ubuntu",
    "instrumentation-urllib3-1 3.11 Ubuntu",
    "instrumentation-urllib3-1 3.12 Ubuntu",
    "instrumentation-urllib3-1 3.9 Ubuntu",
    "instrumentation-wsgi",
    "instrumentation-wsgi 3.10 Ubuntu",
    "instrumentation-wsgi 3.11 Ubuntu",
    "instrumentation-wsgi 3.12 Ubuntu",
    "instrumentation-wsgi 3.9 Ubuntu",
    "opentelemetry-instrumentation",
    "opentelemetry-instrumentation 3.10 Ubuntu",
    "opentelemetry-instrumentation 3.11 Ubuntu",
    "opentelemetry-instrumentation 3.12 Ubuntu",
    "opentelemetry-instrumentation 3.9 Ubuntu",
    "processor-baggage",
    "processor-baggage 3.10 Ubuntu",
    "processor-baggage 3.11 Ubuntu",
    "processor-baggage 3.12 Ubuntu",
    "processor-baggage 3.9 Ubuntu",
    "propagator-aws-xray",
    "propagator-aws-xray-0 3.10 Ubuntu",
    "propagator-aws-xray-0 3.11 Ubuntu",
    "propagator-aws-xray-0 3.12 Ubuntu",
    "propagator-aws-xray-0 3.9 Ubuntu",
    "propagator-aws-xray-1 3.10 Ubuntu",
    "propagator-aws-xray-1 3.11 Ubuntu",
    "propagator-aws-xray-1 3.12 Ubuntu",
    "propagator-aws-xray-1 3.9 Ubuntu",
    "propagator-ot-trace",
    "propagator-ot-trace 3.10 Ubuntu",
    "propagator-ot-trace 3.11 Ubuntu",
    "propagator-ot-trace 3.12 Ubuntu",
    "propagator-ot-trace 3.9 Ubuntu",
    "resource-detector-azure",
    "resource-detector-azure-0 3.10 Ubuntu",
    "resource-detector-azure-0 3.11 Ubuntu",
    "resource-detector-azure-0 3.12 Ubuntu",
    "resource-detector-azure-0 3.9 Ubuntu",
    "resource-detector-azure-1 3.10 Ubuntu",
    "resource-detector-azure-1 3.11 Ubuntu",
    "resource-detector-azure-1 3.12 Ubuntu",
    "resource-detector-azure-1 3.9 Ubuntu",
    "resource-detector-containerid",
    "resource-detector-containerid 3.10 Ubuntu",
    "resource-detector-containerid 3.11 Ubuntu",
    "resource-detector-containerid 3.12 Ubuntu",
    "resource-detector-containerid 3.13 Ubuntu",
    "resource-detector-containerid 3.9 Ubuntu",
    "resource-detector-containerid pypy-3.9 Ubuntu",
    "sdk-extension-aws",
    "sdk-extension-aws-0 3.10 Ubuntu",
    "sdk-extension-aws-0 3.11 Ubuntu",
    "sdk-extension-aws-0 3.12 Ubuntu",
    "sdk-extension-aws-0 3.9 Ubuntu",
    "sdk-extension-aws-1 3.10 Ubuntu",
    "sdk-extension-aws-1 3.11 Ubuntu",
    "sdk-extension-aws-1 3.12 Ubuntu",
    "sdk-extension-aws-1 3.9 Ubuntu",
    "shellcheck",
    "spellcheck",
    "util-http",
    "util-http 3.10 Ubuntu",
    "util-http 3.11 Ubuntu",
    "util-http 3.12 Ubuntu",
    "util-http 3.9 Ubuntu",
  ]
  require_conversation_resolution = true
}

module "branch-protection-rule-opentelemetry-python-contrib-1" {
  source = "./modules/branch-protection-long-term"
  repository_id = module.repo-opentelemetry-python-contrib.node_id
  pattern = "release/*"
  require_code_owner_reviews = false
  enforce_admins = false
  depends_on = [module.branch-protection-rule-opentelemetry-python-contrib-0]
  block_creations = false
}

module "branch-protection-rule-opentelemetry-python-contrib-2" {
  source = "./modules/branch-protection-feature"
  repository_id = module.repo-opentelemetry-python-contrib.node_id
  pattern = "opentelemetrybot/**/**"
  required_status_checks_no_easy_cla = true
  depends_on = [module.branch-protection-rule-opentelemetry-python-contrib-1]
}

module "branch-protection-rule-opentelemetry-python-contrib-3" {
  source = "./modules/branch-protection-long-term"
  repository_id = module.repo-opentelemetry-python-contrib.node_id
  pattern = "package-release/.*"
  require_code_owner_reviews = false
  required_status_checks = false
  required_status_checks_no_easy_cla = true
  enforce_admins = false
  depends_on = [module.branch-protection-rule-opentelemetry-python-contrib-2]
}

module "branch-protection-rule-opentelemetry-python-contrib-4" {
  source = "./modules/branch-protection-feature"
  repository_id = module.repo-opentelemetry-python-contrib.node_id
  pattern = "dependabot/**/*"
  depends_on = [module.branch-protection-rule-opentelemetry-python-contrib-3]
}

